---
#- hosts: 10.42.67.248
- hosts: all
  serial: 1
  gather_facts: yes

  tasks:
  -  name: Root FS usage
     shell: df -h "{{ FS_MOUNTPOINT }}" |awk ' { print $5 } ' |grep -v Use
     register: dfroot

  -  debug:
       msg: "System "{{ inventory_hostname }}"'s "{{ FS_MOUNTPOINT }} "utilisation is "{{ dfroot.stdout }}""
