---
- hosts: 10.42.67.12
  serial: 1
  gather_facts: yes

  tasks:
  - name: Copy file with owner and permissions
      copyfile:
      src: /home/docker/ansible-eg.txt
      dest: /tmp/ansible-eg.txt
      owner: foo
      group: foo
      mode: '0644'
