---
- hosts: all
  serial: 1
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: "ansible-eg.txt"
      dest: "/tmp/ansible-eg.txt"
      owner: foo
      group: foo
      mode: '0644'
