---
- hosts: 10.42.67.248
  serial: 1
  gather_facts: yes

  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: "/tmp/ansible-eg.txt"
      dest: "/tmp/ansible-eg.txt"
      owner: foo
      group: foo
      mode: '0644'
