# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

# Ex 1: Ungrouped hosts, specify before any group headers.

## green.example.com
## blue.example.com
## 192.168.100.1
## 192.168.100.10

# Ex 2: A collection of hosts belonging to the 'webservers' group

## [webservers]
## alpha.example.org
## beta.example.org
## 192.168.1.100
## 192.168.1.110

# If you have multiple hosts following a pattern you can specify
# them like this:

## www[001:006].example.com

# Ex 3: A collection of database servers in the 'dbservers' group

## [dbservers]
## 
## db01.intranet.mydomain.net
## db02.intranet.mydomain.net
## 10.25.1.56
## 10.25.1.57

# Here's another example of host ranges, this time there are no
# leading 0s:

## db-[99:101]-node.example.com


## Lancaster Hosts to Manage
[duncan]
#psy-shiny.lancs.ac.uk has address 10.42.67.248
10.42.67.248 ansible_user=bron ansible_python_interpreter=python3

#sdo-assets2.lancs.ac.uk has address 10.42.67.12
10.42.67.12 ansible_python_interpreter=/usr/bin/python3

#boole.lancs.ac.uk ansible_user=arya
10.42.19.42 ansible_user=arya

#ubudesktop ansible_user=bron
#148.88.208.246 ansible_user=cersei

lec-cpom.lancs.ac.uk ansible_user=bron

#ubudesktop ansible_host=localhost ansible_connection=local ansible_python_interpreter=python3
#ubudesktop ansible_ssh_host=148.88.208.246
