---
- name: Installer With Prompts
  hosts: "{{ HOSTS }}"
  become: true
  become_user: root

  module_defaults:
    apt:
      force_apt_get: yes

  tasks:
   - name: Install software...   
     apt:
      name: "{{ SOFTWARE }}"
      #name: zzuf
      state: latest
      update_cache: yes
     vars:
       ansible_python_interpreter: /usr/bin/python3
        
        
  # name: "{{ SOFTWARE }}"      
  #name: zzuf   
  #become_method: sudo
  #strategy: debug 
  #hosts: "{{ HOSTS }}"  
  #- debug:
  #    msg: "System {{ HOSTS }} has installed {{ SOFTWARE }}"
