---
- name: Testing...   
  hosts: 10.42.67.248
  become: true
  become_user: 'root'
  #become_method: 'sudo'
  #strategy: debug

  module_defaults:
    apt:
      force_apt_get: yes

  tasks:
   - name: Just want to install alien for example...
     apt: 
      name: alien 
      state: present
      update_cache: yes
      
     vars:
      allow_world_readable_tmpfiles: true
      ansible_python_interpreter: "/usr/bin/python3" 
      
