
---
- name: Installer With Prompts
  hosts: "{{ HOSTS }}"
  #become: true
  #become_user: root
  #become_method: sudo
  #strategy: debug

  module_defaults:
    apt:
      force_apt_get: yes

  tasks:
   - name: Just want to install software...   
     apt: 
#      name: "{{ SOFTWARE }}"
      name: zzuf
      state: present
      update_cache: yes
     vars:
       ansible_python_interpreter: /usr/bin/python
      
#   - debug:
 #      msg: "System {{ HOSTS }} has installed {{ SOFTWARE }}"
