---
- hosts: all
  tasks:
  - name: Copy to AWX Specifying a destination path
    fetch: src=/tmp/ansible-eg.txt dest=/tmp/ flat=yes
    when: inventory_hostname == 'lancs-linuxmgmt.lancs.ac.uk'
  - name: Copy to remote machine
    copy: src=/tmp/ansible-eg.txt dest=/tmp/
    when: inventory_hostname == 'psy-shiny.lancs.ac.uk'
